
The following have been reloaded with a version change:
  1) cudnn/8.8.1.3 => cudnn/8.9.2.26

Reading folder: /nfs/nas22/fs2202/biol_bc_kleele_2/Joshua/240118_RPE1_FUCCI_stacks
/nfs/nas22/fs2202/biol_bc_kleele_2/Joshua/240118_RPE1_FUCCI_stacks/240118_RPE1_FUCCI_pkmodeepred_11/240118_RPE1_FUCCI_pkmodeepred_11_MMStack_Pos6.ome.tif
header 4 : b'<?xm'
header[:2]:  b'l '
Traceback (most recent call last):
  File "/cluster/home/jsammet/iSIM/deconvolution/script_folder.py", line 35, in <module>
    cuda_decon.decon_ome_stack(file.as_posix(), params=parameters)
  File "/cluster/home/jsammet/iSIM/deconvolution/cuda_decon.py", line 135, in decon_ome_stack
    size_t = int(my_dict['OME']['Image']["Pixels"]["@SizeT"])
                 ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'Image'
/nfs/nas22/fs2202/biol_bc_kleele_2/Joshua/240118_RPE1_FUCCI_stacks/240118_RPE1_FUCCI_pkmodeepred_3/240118_RPE1_FUCCI_pkmodeepred_3_MMStack_Pos12.ome.tif
header 4 : b'<?xm'
header[:2]:  b'l '
Traceback (most recent call last):
  File "/cluster/home/jsammet/iSIM/deconvolution/script_folder.py", line 35, in <module>
    cuda_decon.decon_ome_stack(file.as_posix(), params=parameters)
  File "/cluster/home/jsammet/iSIM/deconvolution/cuda_decon.py", line 135, in decon_ome_stack
    size_t = int(my_dict['OME']['Image']["Pixels"]["@SizeT"])
                 ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'Image'
